chageFileValidation

diff --git a/.github/workflows/pr_validacion.yml b/.github/workflows/pr_validacion.yml
--- a/.github/workflows/pr_validacion.yml
+++ b/.github/workflows/pr_validacion.yml
@@ -118,19 +118,34 @@ jobs:
       
       - name: 🛂 Autenticarse en Salesforce con JWT
         env:
+          BRANCH_NAME: ${{ github.ref_name }}
           SFDX_CLIENT_ID: ${{ env.CLIENT_ID }}
           SFDX_USERNAME: ${{ env.USERNAME }}
           SFDX_URL: ${{ env.LOGIN_URL }}
-          SFDX_JWT_KEY: ${{ vars.SFDX_JWT_KEY_INTEGRA }}
+          SFDX_JWT_KEY_INTEGRA: ${{ vars.SFDX_JWT_KEY_INTEGRA }}
+          SFDX_JWT_KEY_UAT: ${{ vars.SFDX_JWT_KEY_UAT }}
+          SFDX_JWT_KEY_PRO: ${{ vars.SFDX_JWT_KEY_PRO }}
         run: |
 
-          echo "$SFDX_JWT_KEY" > server.key
-          sf org login jwt \
-            --client-id "$SFDX_CLIENT_ID" \
-            --jwt-key-file server.key \
-            --username "$SFDX_USERNAME" \
-            --instance-url "$SFDX_URL" \
-            --alias SF
+          if [[ "$BRANCH_NAME" == "main" ]]; then
+            echo "$SFDX_JWT_KEY_PRO" > server.key
+          elif [[ "$BRANCH_NAME" == "uat" ]]; then
+           echo "$SFDX_JWT_KEY_UAT" > server.key
+          elif [[ "$BRANCH_NAME" == "Integra" ]]; then
+            echo "$SFDX_JWT_KEY_INTEGRA" > server.key
+          fi
+
+          if [[ -f "server.key" ]]; then
+            sf org login jwt \
+              --client-id "$SFDX_CLIENT_ID" \
+              --jwt-key-file server.key \
+              --username "$SFDX_USERNAME" \
+              --instance-url "$SFDX_URL" \
+              --alias SF
+          else
+            echo "❌ Error: server.key not found, aborting login"
+            exit 1
+          fi
 
       - name: ✍ Verify Authentication
         run: |
